import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

premier_league = pd.read_csv("premier_league.csv")
print(premier_league.head())

city_data = premier_league[premier_league.team == "Manchester City"] 
print(city_data.head())

plt.figure(figsize=(15,8))
plt.title("Broj golova Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.grid(True)
plt.plot(city_data.season,city_data.goals,marker = "o")
plt.xticks(rotation=60)
plt.savefig("Broj golova Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()


plt.figure(figsize=(15,8))
plt.title("Broj golova Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.grid(True)
plt.bar(city_data.season,city_data.goals)
plt.xticks(rotation=60)
plt.savefig("Broj golova Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj pobeda Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj pobeda")
plt.grid(True)
plt.plot(city_data.season,city_data.wins,marker = "o")
plt.xticks(rotation=60)
plt.savefig("Broj pobeda Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj pobeda Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj pobeda")
plt.bar(city_data.season,city_data.wins)
plt.xticks(rotation=60)
plt.savefig("Broj pobeda Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()


plt.figure(figsize=(15,8))
plt.title("Broj poraza Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj poraza")
plt.grid(True)
plt.bar(city_data.season,city_data.losses)
plt.xticks(rotation=60)
plt.yticks(np.arange(1,20))
plt.savefig("Broj poraza Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()


plt.figure(figsize=(15,8))
plt.title("Broj zutih kartona Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj zutih kartona")
plt.bar(city_data.season,city_data.total_yel_card,color="yellow")
plt.xticks(rotation=60)
plt.savefig("Broj zutih kartona Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj crvenih kartona Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj crvenih kartona")
plt.bar(city_data.season,city_data.total_red_card,color="red")
plt.xticks(rotation=60)
plt.savefig("Broj crvenih kartona Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Ukupan broj suteva Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj suteva")
plt.bar(city_data.season,city_data.total_scoring_att)
plt.xticks(rotation=60)
plt.savefig("Ukupan broj suteva Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj suteva u okvir gola Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj suteva u okvir gola")
plt.bar(city_data.season,city_data.ontarget_scoring_att,color="orange")
plt.xticks(rotation=60)
plt.savefig("Broj suteva u okvir gola Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj pogodjenih stativa i precki Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj pogodjenih stativa i precki")
plt.bar(city_data.season,city_data.hit_woodwork,color="purple")
plt.xticks(rotation=60)
plt.savefig("Broj pogodjenih stativa i precki Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih glavom Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.att_hd_goal,color="brown")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih glavom Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih iz penala Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.att_pen_goal,color="green")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih iz penala Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih iz slobodnih udaraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.att_freekick_goal,color="pink")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih iz slobodnih udaraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih iz sesnaesterca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.att_ibox_goal,color="grey")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih iz sesnaesterca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih van sesnaesterca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.att_obox_goal,color="g")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih van sesnaesterca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj golova postignutih iz kontranapada Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.goal_fastbreak,color="r")
plt.xticks(rotation=60)
plt.savefig("Broj golova postignutih iz kontranapada Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj autogolova Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj autogolova")
plt.bar(city_data.season,city_data.own_goals,color="orange")
plt.xticks(rotation=60)
plt.savefig("Broj autogolova Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj ofsajd pozicija Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj ofsajda")
plt.bar(city_data.season,city_data.total_offside,color="black")
plt.xticks(rotation=60)
plt.savefig("Broj ofsajd pozicija Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj utakmica bez primljenog gola Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("broj utakmica")
plt.bar(city_data.season,city_data.clean_sheet,color="green")
plt.xticks(rotation=60)
plt.yticks(np.arange(1,25))
plt.savefig("Broj utakmica bez primljenog gola Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj primljenih golova Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj primljenih golova")
plt.bar(city_data.season,city_data.goals_conceded)
plt.xticks(rotation=60)
plt.savefig("Broj primljenih golova Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj dosudjenih penala protiv Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj penala")
plt.bar(city_data.season,city_data.penalty_conceded,color="r")
plt.xticks(rotation=60)
plt.savefig("Broj dosudjenih penala protiv Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj primljenih golova iz penala protiv Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj golova")
plt.bar(city_data.season,city_data.pen_goals_conceded,color="g")
plt.xticks(rotation=60)
plt.savefig("Broj primljenih golova iz penala protiv Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()


plt.figure(figsize=(15,8))
plt.title("Broj odbranjenih penala Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj odbranjenih penala")
plt.bar(city_data.season,city_data.penalty_save)
plt.xticks(rotation=60)
plt.yticks(np.arange(1,6))
plt.savefig("Broj odbranjenih penala Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,9))
plt.title("Broj dodavanja Man City-ija po sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj dodavanja")
plt.bar(city_data.season,city_data.total_pass,color="green")
plt.xticks(rotation=60)
plt.savefig("Broj dodavanja Man City-ija po sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,9))
plt.title("Broj dugackih lopti Man City-ija u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Dugacke lopte")
plt.bar(city_data.season,city_data.total_long_balls,color="purple")
plt.xticks(rotation=60)
plt.savefig("Broj dugackih lopti Man City-ija u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,9))
plt.title("Broj dodavanja unazad Man City-ija u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("broj dodavanja")
plt.bar(city_data.season,city_data.backward_pass,color="orange")
plt.xticks(rotation=60)
plt.savefig("Broj dodavanja unazad Man City-ija u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,9))
plt.title("Broj dodira sa loptom Man City-ija u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("broj dodira")
plt.bar(city_data.season,city_data.touches)
plt.xticks(rotation=60)
plt.savefig("Broj dodira sa loptom Man City-ija u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj kornera Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj kornera")
plt.bar(city_data.season,city_data.corner_taken,color="brown")
plt.savefig("Broj kornera Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()


plt.figure(figsize=(15,8))
plt.title("Broj startova igraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj startova")
plt.bar(city_data.season,city_data.total_tackle,color="black")
plt.xticks(rotation=60)
plt.savefig("Broj startova igraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj uspesnih startova poslednjeg igraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj startova")
plt.bar(city_data.season,city_data.last_man_tackle,color="r")
plt.xticks(rotation=60)
plt.yticks(np.arange(1,20))
plt.savefig("Broj uspesnih startova poslednjeg igraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj blokiranih suteva u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj bloiranih suteva")
plt.bar(city_data.season,city_data.outfielder_block)
plt.xticks(rotation=60)
plt.savefig("Broj blokiranih suteva u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj presecenih dodavanja igraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj presecenih dodavanja")
plt.bar(city_data.season,city_data.interception)
plt.xticks(rotation=60)
plt.savefig("Broj presecenih dodavanja igraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj uhvacenih visokih lopti golmana Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj uhvacenih lopti")
plt.bar(city_data.season,city_data.total_high_claim)
plt.xticks(rotation=60)
plt.savefig("Broj uhvacenih visokih lopti golmana Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj 'boksovanih' lopti golmana Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj boksovanih lopti")
plt.bar(city_data.season,city_data.punches,color="purple")
plt.xticks(rotation=60)
plt.savefig("Broj 'boksovanih' lopti golmana Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj odbrana golmana Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj odbrana golmana")
plt.bar(city_data.season,city_data.saves,color="g")
plt.xticks(rotation=60)
plt.savefig("Broj odbrana golmana Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj izbijenih lopti igraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj izbijenih lopti")
plt.bar(city_data.season,city_data.total_clearance)
plt.xticks(rotation=60)
plt.savefig("Broj izbijenih lopti igraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()

plt.figure(figsize=(15,8))
plt.title("Broj izbijenih lopti sa gol linije igraca Man City-ja u sezonama 2006-2018",fontdict={"fontweight":"bold"})
plt.xlabel("Sezona")
plt.ylabel("Broj izbijenih lopti")
plt.bar(city_data.season,city_data.clearance_off_line,color="red")
plt.xticks(rotation=60)
plt.savefig("Broj izbijenih lopti sa gol linije igraca Man City-ja u sezonama 2006-2018",dpi=300)
plt.show()





















